import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/components/layout/SiteShell";
import { CONTACT_EMAIL } from "@/lib/contact";
import { comingSoonFunctions } from "@/data/catalog-coming-soon";
import { getPublicCatalog } from "@/lib/publicCatalog";
import { describePermission } from "@/lib/publicPermissions";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export async function generateMetadata({params}:{params:Promise<{worker:string}>}):Promise<Metadata>{const slug=(await params).worker;const item=(await getPublicCatalog()).flatMap(f=>f.workers).find(w=>w.slug===slug);const planned=comingSoonFunctions.flatMap(f=>f.workers).find(name=>slugify(name)===slug);const title=`${item?.name??planned??"Worker"} | FAIVR`;const description=item?.role??"Planned governed AI worker for your Truchsess.";return {title,description,openGraph:{title,description}}}
export default async function Page({params}:{params:Promise<{worker:string}>}){const slug=(await params).worker;const available=(await getPublicCatalog()).flatMap(x=>x.workers.map(w=>({function:x,...w}))).find(w=>(("slug"in w&&w.slug)||slugify(w.name))===slug);const planned=comingSoonFunctions.flatMap(f=>f.workers.map(name=>({function:f,name}))).find(w=>slugify(w.name)===slug);if(!available&&!planned)notFound();if(planned&&!available)return <SiteShell><div className="mx-auto max-w-[900px] px-4 py-14 sm:px-8"><Link href={`/catalog/${planned.function.slug}`} className="inline-flex min-h-11 min-w-11 items-center rounded-full bg-white px-3 text-sm font-bold text-[var(--accent)]">← {planned.function.name}</Link><p className="mt-8 inline-flex rounded-full bg-white px-3 py-1 text-xs font-bold tracking-[.14em] text-[var(--accent)]">COMING SOON</p><h1 className="mt-3 text-5xl font-extrabold">{planned.name}</h1><p className="mt-5 text-lg text-[var(--body)]">{planned.function.summary}</p><p className="mt-8 rounded-3xl bg-white p-6 text-[var(--body)]">Permissions, example tasks, proof of origin, and package details will be published with the package.</p><a className="mt-6 inline-block rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white" href={`mailto:${CONTACT_EMAIL}`}>Tell me when it is ready</a></div></SiteShell>;if(!available)notFound();return <SiteShell><div className="mx-auto max-w-[900px] px-4 py-14 sm:px-8"><Link href={`/catalog/${available.function.slug}`} className="inline-flex min-h-11 min-w-11 items-center rounded-full bg-white px-3 text-sm font-bold text-[var(--accent)]">← {available.function.name}</Link><h1 className="mt-8 text-5xl font-extrabold">{available.name}</h1><p className="mt-4 text-lg text-[var(--body)]">{available.role}</p><section className="mt-10 rounded-3xl bg-white p-7"><h2 className="text-2xl font-bold">{available.permissions.length} permissions. You approve each one.</h2><ul className="mt-4 space-y-2 text-[var(--body)]">{available.permissions.map(p=><li key={p}>{describePermission(p)}</li>)}</ul><p className="mt-6 text-sm font-bold">Never: acts without a task someone started; changes its own permissions; sees other workers&apos; files; spends money.</p></section><section className="mt-8 rounded-3xl bg-[var(--ink)] p-7 text-[var(--dark-text)]"><p className="text-xs font-bold tracking-[.14em]">PROOF OF ORIGIN · SIGNED</p><p className="mt-5">Publisher: {available.publisherName}</p><p>Package id: {available.id}</p><p>Version: {available.version}</p><p className="font-mono text-sm break-all">Publisher key: {available.publisherKeyId}<br/>Package digest: {available.digest}</p><p className="mt-5 text-sm text-[#C3C5DA]">Your Truchsess checks the signature and this digest before it installs the worker. The same digest is shown on your appliance.</p></section><p className="mt-8 rounded-3xl bg-white p-6 font-bold">Subscribe on your Truchsess, not on this site.</p></div></SiteShell>}
