import type { Metadata } from "next";
import { SiteShell } from "@/components/layout/SiteShell";
import { getPublicCatalog } from "@/lib/publicCatalog";

export const metadata: Metadata = { title: "Trust | FAIVR", description: "Trust you can check, not trust we ask for.", openGraph: { title: "Trust | FAIVR", description: "Trust you can check, not trust we ask for." } };
const rules = [["Signed, or not installed", "Your appliance checks a package before it installs it."], ["Only what you allow", "You approve each requested permission."], ["Nothing on its own", "Agents act only on a task someone started."], ["Every run on the record", "Your appliance reports every run and what it cost."]];

export default async function Page() {
  const catalog = await getPublicCatalog();
  const first = catalog[0];
  return <SiteShell><div className="mx-auto max-w-[1220px] px-4 py-14 sm:px-8"><p className="inline-flex rounded-full bg-white px-3 py-1 text-xs font-bold tracking-[.14em] text-[var(--accent)]">TRUST</p><h1 className="mt-3 text-5xl font-extrabold tracking-[-.06em] sm:text-7xl">Trust you can check, not trust we ask for.</h1><section className="mt-10 grid gap-4 md:grid-cols-4">{rules.map(([title, copy]) => <article key={title} className="rounded-3xl bg-white p-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--body)]">{copy}</p></article>)}</section><section className="mt-12 rounded-3xl bg-white p-7"><h2 className="text-2xl font-bold">Publishers</h2><p className="mt-3 text-[var(--body)]">You decide whom your appliance trusts. Old School reviews every package before it enters this catalog.</p></section><section className="mt-8 rounded-3xl bg-white p-7"><h2 className="text-2xl font-bold">Check a package yourself</h2>{first ? <p className="mt-3 font-mono text-sm break-all">{first.workers[0]?.publisherKeyId} · {first.workers[0]?.digest}</p> : <p className="mt-3 text-[var(--body)]">No public package is available to check yet.</p>}</section><section className="mt-8 overflow-x-auto rounded-3xl bg-white p-7"><h2 className="text-2xl font-bold">What leaves your appliance, and what never does</h2><table className="mt-5 w-full text-left text-sm"><tbody><tr><th>FAIVR store</th><td>Package and subscription information needed by the store.</td></tr><tr><th>Polar</th><td>Payment information for the merchant of record.</td></tr><tr><th>AI model provider</th><td>Only what your selected model service needs to run a task.</td></tr></tbody></table></section><section className="mt-8"><h2 className="text-2xl font-bold">The store is open source</h2><a className="mt-3 inline-flex min-h-11 min-w-11 items-center rounded-full bg-white px-4 font-bold text-[var(--accent)]" href="https://github.com/oldschool-ag/Faivr">View the store code on GitHub</a></section></div></SiteShell>;
}
