"use client";

import Link from "next/link";
import { Download, RefreshCw, ShieldCheck } from "lucide-react";
import { SiteShell } from "@/components/layout/SiteShell";
import { Card } from "@/components/ui/Card";
import { buttonVariants } from "@/components/ui/Button";

export default function CompanyOsMarketplacePage(){return <SiteShell><main className="mx-auto max-w-6xl px-6 py-16"><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-700">Company OS marketplace</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-[-.05em] text-slate-950">Install governed agent packages into your Company OS.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Browse versioned manifests, hand subscription checkout to FAIVR, and keep installation, updates, uninstall evidence, and billing state visible end to end.</p><div className="mt-10 grid gap-4 md:grid-cols-3"><Card padding="lg"><Download className="h-5 w-5 text-sky-600"/><h2 className="mt-5 font-semibold">Entitled delivery</h2><p className="mt-2 text-sm leading-6 text-slate-600">Package metadata and checksums become available only after subscription entitlement.</p></Card><Card padding="lg"><RefreshCw className="h-5 w-5 text-indigo-600"/><h2 className="mt-5 font-semibold">Compatible updates</h2><p className="mt-2 text-sm leading-6 text-slate-600">Company OS can compare installed and published versions before activation.</p></Card><Card padding="lg"><ShieldCheck className="h-5 w-5 text-emerald-600"/><h2 className="mt-5 font-semibold">Verified offboarding</h2><p className="mt-2 text-sm leading-6 text-slate-600">Billing stops only after a scoped, signed deletion receipt is verified.</p></Card></div><div className="mt-8 rounded-[28px] border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Connect from Company OS</h2><p className="mt-2 text-sm leading-6 text-slate-600">The authenticated catalog and lifecycle API is ready for a configured Company OS tenant. Package contents are never inferred from public metadata.</p><Link href="/docs" className={`${buttonVariants({variant:"secondary",size:"md"})} mt-5`}>Read integration notes</Link></div></main></SiteShell>}
