CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS company_os_packages (id text PRIMARY KEY CHECK(id ~ '^faivr\.agent\.[a-z0-9]+([._-][a-z0-9]+)*$'), slug text UNIQUE NOT NULL, name text NOT NULL, summary text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_os_publishers (key_id text PRIMARY KEY, public_key text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_os_package_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id text NOT NULL REFERENCES company_os_packages(id), version text NOT NULL CHECK(version ~ '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$'), status text NOT NULL CHECK(status IN ('draft','published','withdrawn')), manifest jsonb NOT NULL, publisher_key_id text REFERENCES company_os_publishers(key_id), publisher_signature text NOT NULL, artifact_url text NOT NULL, artifact_sha256 text NOT NULL CHECK(artifact_sha256 ~ '^sha256:[a-f0-9]{64}$'), monthly_price_cents integer NOT NULL CHECK(monthly_price_cents >= 0), stripe_price_id text, min_company_os_version text NOT NULL, published_at timestamptz, UNIQUE(package_id,version));
ALTER TABLE company_os_package_versions ADD COLUMN IF NOT EXISTS release_notes text CHECK(release_notes IS NULL OR char_length(release_notes) <= 1000);
CREATE TABLE IF NOT EXISTS company_os_instance_keys (tenant_id uuid NOT NULL, instance_id uuid NOT NULL, key_id text NOT NULL, public_key text NOT NULL, not_before timestamptz NOT NULL DEFAULT now(), not_after timestamptz, revoked_at timestamptz, PRIMARY KEY(tenant_id,instance_id,key_id));
CREATE INDEX IF NOT EXISTS company_os_instance_keys_overlap_idx ON company_os_instance_keys(tenant_id,instance_id,not_before,not_after) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS company_os_request_nonces (tenant_id text NOT NULL, instance_id text NOT NULL, nonce text NOT NULL, expires_at timestamptz NOT NULL, PRIMARY KEY(tenant_id,instance_id,nonce));
CREATE INDEX IF NOT EXISTS company_os_request_nonces_expiry_idx ON company_os_request_nonces(expires_at);
CREATE TABLE IF NOT EXISTS company_os_installations (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, package_id text NOT NULL REFERENCES company_os_packages(id), desired_version_id uuid REFERENCES company_os_package_versions(id), installed_version_id uuid REFERENCES company_os_package_versions(id), subscription_id uuid UNIQUE NOT NULL, checkout_session_id uuid UNIQUE, local_agent_definition_id text, installation_state text NOT NULL CHECK(installation_state IN ('selected','payment_pending','entitled','downloading','installing','active','update_available','disabled','uninstall_pending','removed','failed')), subscription_state text NOT NULL CHECK(subscription_state IN ('checkout_pending','active','past_due','suspended','cancellation_pending_uninstall','cancel_at_period_end','cancelled')), stripe_checkout_session_id text UNIQUE, stripe_subscription_id text UNIQUE, entitled_at timestamptz, installed_at timestamptz, uninstall_request_id uuid, uninstall_requested_at timestamptz, receipt_accepted_at timestamptz, billing_cancel_effective_at timestamptz, billing_stopped_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE company_os_installations ADD COLUMN IF NOT EXISTS checkout_session_id uuid UNIQUE;
ALTER TABLE company_os_installations ALTER COLUMN stripe_checkout_session_id TYPE text USING stripe_checkout_session_id::text;
CREATE INDEX IF NOT EXISTS company_os_installations_tenant_idx ON company_os_installations(tenant_id,created_at DESC);
CREATE TABLE IF NOT EXISTS company_os_idempotency (tenant_id text NOT NULL, idempotency_key text NOT NULL, operation text NOT NULL, request_hash text NOT NULL, status text NOT NULL CHECK(status IN ('processing','completed')), response_body jsonb, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, expires_at timestamptz NOT NULL, PRIMARY KEY(tenant_id,idempotency_key,operation));
CREATE INDEX IF NOT EXISTS company_os_idempotency_expiry_idx ON company_os_idempotency(expires_at);
CREATE TABLE IF NOT EXISTS company_os_archive_receipts (receipt_id uuid PRIMARY KEY, tenant_id uuid NOT NULL, instance_id uuid NOT NULL, installation_id uuid NOT NULL REFERENCES company_os_installations(id), payload jsonb NOT NULL, signature text NOT NULL, accepted_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_os_uninstall_receipts (receipt_id uuid PRIMARY KEY, tenant_id uuid NOT NULL, instance_id uuid NOT NULL, installation_id uuid NOT NULL REFERENCES company_os_installations(id), uninstall_request_id uuid NOT NULL, subscription_id uuid NOT NULL, nonce text NOT NULL, payload jsonb NOT NULL, signature text NOT NULL, accepted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,instance_id,nonce));
CREATE TABLE IF NOT EXISTS company_os_billing_acknowledgements (event_id uuid PRIMARY KEY, receipt_id uuid NOT NULL, subscription_id uuid NOT NULL, receipt_state text NOT NULL CHECK(receipt_state IN ('accepted','rejected')), subscription_state text NOT NULL CHECK(subscription_state IN ('checkout_pending','active','past_due','suspended','cancellation_pending_uninstall','cancel_at_period_end','cancelled')), effective_at timestamptz NOT NULL, rejection_reason text, payload jsonb NOT NULL, signature text NOT NULL, UNIQUE(receipt_id,subscription_state));
CREATE TABLE IF NOT EXISTS company_os_webhook_events (provider text NOT NULL, event_id text NOT NULL, payload jsonb NOT NULL, processed_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(provider,event_id));
CREATE TABLE IF NOT EXISTS company_os_audit_events (id bigserial PRIMARY KEY, tenant_id text NOT NULL, installation_id uuid, event_type text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
-- Private store (T6b): Old School as the only publisher, function bundles priced in Stripe, per-appliance enrolment.
ALTER TABLE company_os_publishers ADD COLUMN IF NOT EXISTS publisher_id text;
ALTER TABLE company_os_publishers ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE company_os_instance_keys ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE company_os_instance_keys ADD COLUMN IF NOT EXISTS enrolled_at timestamptz;
ALTER TABLE company_os_instance_keys ADD COLUMN IF NOT EXISTS last_contact_at timestamptz;
CREATE TABLE IF NOT EXISTS company_os_function_bundles (id text PRIMARY KEY CHECK(id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'), name text NOT NULL, description text NOT NULL, stripe_price_id text UNIQUE, monthly_price_cents integer NOT NULL CHECK(monthly_price_cents >= 0), currency text NOT NULL DEFAULT 'chf', status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','retired')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_os_bundle_packages (bundle_id text NOT NULL REFERENCES company_os_function_bundles(id), package_id text NOT NULL REFERENCES company_os_packages(id), added_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(bundle_id,package_id));
CREATE TABLE IF NOT EXISTS company_os_package_artifacts (version_id uuid PRIMARY KEY REFERENCES company_os_package_versions(id), artifact bytea NOT NULL, artifact_bytes integer NOT NULL, artifact_sha256 text NOT NULL CHECK(artifact_sha256 ~ '^sha256:[a-f0-9]{64}$'), uploaded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_os_bundle_subscriptions (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, instance_id uuid NOT NULL, bundle_id text NOT NULL REFERENCES company_os_function_bundles(id), checkout_session_id uuid UNIQUE, stripe_checkout_session_id text UNIQUE, stripe_subscription_id text UNIQUE, subscription_state text NOT NULL CHECK(subscription_state IN ('checkout_pending','active','past_due','suspended','cancellation_pending_uninstall','cancel_at_period_end','cancelled')), entitled_at timestamptz, cancel_effective_at timestamptz, stopped_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS company_os_bundle_subscriptions_tenant_idx ON company_os_bundle_subscriptions(tenant_id,bundle_id,created_at DESC);
ALTER TABLE company_os_installations ADD COLUMN IF NOT EXISTS bundle_subscription_id uuid REFERENCES company_os_bundle_subscriptions(id);
ALTER TABLE company_os_installations ADD COLUMN IF NOT EXISTS instance_id uuid;
-- several installations of one bundle share the bundle's subscription identity
ALTER TABLE company_os_installations DROP CONSTRAINT IF EXISTS company_os_installations_subscription_id_key;
CREATE INDEX IF NOT EXISTS company_os_installations_subscription_idx ON company_os_installations(subscription_id);
CREATE TABLE IF NOT EXISTS company_os_enrolment_codes (code_hash text PRIMARY KEY, tenant_id uuid NOT NULL, label text NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, used_at timestamptz, instance_id uuid, key_id text);
-- T6b.1: billing through a provider interface (Polar by default, Stripe as the second implementation).
-- A bundle carries the Polar product id of its recurring product; provider objects are opaque ids next to the state.
ALTER TABLE company_os_function_bundles ADD COLUMN IF NOT EXISTS polar_product_id text UNIQUE;
ALTER TABLE company_os_function_bundles ADD COLUMN IF NOT EXISTS public_listing boolean NOT NULL DEFAULT false;
ALTER TABLE company_os_packages ADD COLUMN IF NOT EXISTS public_listing boolean NOT NULL DEFAULT false;
ALTER TABLE company_os_bundle_subscriptions ADD COLUMN IF NOT EXISTS billing_provider text;
ALTER TABLE company_os_bundle_subscriptions ADD COLUMN IF NOT EXISTS provider_checkout_id text;
ALTER TABLE company_os_bundle_subscriptions ADD COLUMN IF NOT EXISTS provider_subscription_id text;
ALTER TABLE company_os_bundle_subscriptions ADD COLUMN IF NOT EXISTS provider_customer_id text;
UPDATE company_os_bundle_subscriptions SET billing_provider='stripe', provider_checkout_id=stripe_checkout_session_id, provider_subscription_id=stripe_subscription_id WHERE billing_provider IS NULL AND (stripe_checkout_session_id IS NOT NULL OR stripe_subscription_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS company_os_bundle_subscriptions_provider_checkout_idx ON company_os_bundle_subscriptions(billing_provider,provider_checkout_id);
CREATE UNIQUE INDEX IF NOT EXISTS company_os_bundle_subscriptions_provider_subscription_idx ON company_os_bundle_subscriptions(billing_provider,provider_subscription_id);
-- the owner's email, given when the enrolment code is issued, pre-fills the provider's checkout (optional)
ALTER TABLE company_os_enrolment_codes ADD COLUMN IF NOT EXISTS owner_email text;
